name: env4
channels:
  - pytorch
  - rapidsai
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - aom=3.6.1=h59595ed_0
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.9.0=h92a005d_16
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.5=h0c2b49e_1
  - aws-c-http=0.10.2=hee85082_3
  - aws-c-io=0.21.0=h1d8da38_1
  - aws-c-mqtt=0.13.1=h46c1de9_4
  - aws-c-s3=0.8.3=h9cdc349_1
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.33.0=h186f887_0
  - aws-sdk-cpp=1.11.510=h455e09b_15
  - azure-core-cpp=1.15.0=h5cfcd09_0
  - azure-identity-cpp=1.11.0=hb5324b0_1
  - azure-storage-blobs-cpp=12.13.0=hf182047_2
  - azure-storage-common-cpp=12.10.0=h40e822a_1
  - azure-storage-files-datalake-cpp=12.12.0=h141ff2a_2
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bokeh=3.7.3=pyhd8ed1ab_0
  - brotli-python=1.1.0=py310hf71b8c6_3
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.1.0=pyhd8ed1ab_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cuda-bindings=12.9.0=py310h2aa5cc4_1
  - cuda-cccl_linux-64=12.4.127=ha770c72_2
  - cuda-crt-dev_linux-64=12.4.131=ha770c72_1
  - cuda-crt-tools=12.4.131=ha770c72_1
  - cuda-cudart=12.4.127=he02047a_2
  - cuda-cudart-dev=12.4.127=he02047a_2
  - cuda-cudart-dev_linux-64=12.4.127=h85509e4_2
  - cuda-cudart-static=12.4.127=he02047a_2
  - cuda-cudart-static_linux-64=12.4.127=h85509e4_2
  - cuda-cudart_linux-64=12.4.127=h85509e4_2
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-libraries=12.4.1=ha770c72_1
  - cuda-nvcc-dev_linux-64=12.4.131=ha770c72_1
  - cuda-nvcc-impl=12.4.131=hd3aeb46_1
  - cuda-nvcc-tools=12.4.131=hd3aeb46_1
  - cuda-nvrtc=12.4.127=he02047a_2
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-nvvm-dev_linux-64=12.4.131=ha770c72_1
  - cuda-nvvm-impl=12.4.131=h59595ed_1
  - cuda-nvvm-tools=12.4.131=h59595ed_1
  - cuda-opencl=12.4.127=he02047a_1
  - cuda-profiler-api=12.4.127=ha770c72_2
  - cuda-python=12.9.0=pyhd4762b7_2
  - cuda-runtime=12.4.1=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - cudf=25.02.02=cuda12_py310_250303_g8139f3c84f_0
  - cuml=25.02.01=cuda12_py310_250303_g23773cd56_0
  - cupy=13.5.1=py310h8c3aed4_1
  - cupy-core=13.5.1=py310h1ea0ae5_1
  - cytoolz=1.0.1=py310ha75aee5_0
  - dask=2024.12.1=pyhd8ed1ab_0
  - dask-core=2024.12.1=pyhd8ed1ab_0
  - dask-cuda=25.02.00=py310_250213_g4c663f5_0
  - dask-cudf=25.02.02=cuda12_py310_250303_g8139f3c84f_0
  - dask-expr=1.1.21=pyhd8ed1ab_0
  - distributed=2024.12.1=pyhd8ed1ab_0
  - distributed-ucxx=0.42.00=py3.10_250213_g762a6ed_0
  - dlpack=0.8=h59595ed_3
  - fastrlock=0.8.3=py310h8c668a6_1
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - filelock=3.18.0=pyhd8ed1ab_0
  - fmt=11.0.2=h07f6e7f_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310he8512ff_0
  - gnutls=3.7.9=hb077bed_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py310hea1e86d_100
  - hdf5=1.14.6=nompi_h6e4c0c1_102
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs-lite=2019.12.3=py310h261611a_8
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=19.0.1=h94aa55a_22_cpu
  - libarrow-acero=19.0.1=h635bf11_22_cpu
  - libarrow-dataset=19.0.1=h635bf11_22_cpu
  - libarrow-substrait=19.0.1=h3f74fd7_22_cpu
  - libasprintf=0.25.1=h8e693c7_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=16_linux64_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.4.5.8=he02047a_2
  - libcublas-dev=12.4.5.8=he02047a_2
  - libcudf=25.02.02=cuda12_250303_g8139f3c84f_0
  - libcufft=11.2.1.3=he02047a_2
  - libcufile=1.9.1.3=he02047a_2
  - libcufile-dev=1.9.1.3=he02047a_2
  - libcuml=25.02.01=cuda12_250303_g23773cd56_0
  - libcumlprims=25.02.00=cuda12_250213_g5eeba45_0
  - libcurand=10.3.5.147=he02047a_2
  - libcurand-dev=10.3.5.147=he02047a_2
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.6.1.9=he02047a_2
  - libcusolver-dev=11.6.1.9=he02047a_2
  - libcusparse=12.3.1.170=he02047a_2
  - libcusparse-dev=12.3.1.170=he02047a_2
  - libcuvs=25.02.01=cuda12_250303_g20b6775_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran-ng=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.73.1=h1e535eb_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkvikio=25.02.01=cuda12_250227_g8fecf06_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.2.5.30=he02047a_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.4.127=he02047a_2
  - libnvjitlink=12.4.127=he02047a_2
  - libnvjpeg=12.3.1.117=he02047a_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=19.0.1=h790f06f_22_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libprotobuf=6.31.1=h9ef548d_1
  - libraft=25.02.00=cuda12_250213_gbdcc918d_0
  - libraft-headers=25.02.00=cuda12_250213_gbdcc918d_0
  - libraft-headers-only=25.02.00=cuda12_250213_gbdcc918d_0
  - libre2-11=2025.06.26=h7064273_1
  - librmm=25.02.00=cuda12_250213_g39b4ccdb_0
  - libsqlite=3.50.2=hee844dc_2
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.7=h4e0b6ca_0
  - libtasn1=4.20.0=hb9d3cd8_0
  - libthrift=0.22.0=h093b73b_0
  - libtiff=4.7.0=hf01ce69_5
  - libucxx=0.42.00=cuda12_250213_g762a6ed_0
  - libudev1=257.7=hbe16f8c_0
  - libunistring=0.9.10=h7f98852_0
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.13.1=h59595ed_0
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmlite=0.43.0=py310h1a6248f_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py310h80b8a69_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py310h89163eb_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py310h3788b33_0
  - narwhals=1.46.0=pyhe01879c_0
  - nccl=2.27.6.1=h9b8ff78_0
  - ncurses=6.5=h2d0b736_3
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numba=0.60.0=py310h5dc88bb_0
  - numba-cuda=0.2.0=pyh267e887_0
  - numpy=1.26.4=py310hb13e2d6_0
  - nvcomp=4.2.0.11=h791f646_1
  - nvidia-ml-py=12.575.51=pyhd8ed1ab_0
  - nvtx=0.2.12=py310ha75aee5_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.1=h7b32b05_0
  - orc=2.1.3=h61e0c1e_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310h5eaa309_3
  - partd=1.4.2=pyhd8ed1ab_0
  - pillow=11.3.0=py310h7e6dc6c_0
  - pip=25.1.1=pyh8b19718_0
  - poselib=2.0.4=py310hf71b8c6_4
  - prometheus-cpp=1.3.0=ha5d0236_0
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=19.0.1=py310hff52083_0
  - pyarrow-core=19.0.1=py310hac404ae_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pykdtree=1.4.2=py310haaf2d95_0
  - pylibcudf=25.02.02=cuda12_py310_250303_g8139f3c84f_0
  - pylibraft=25.02.00=cuda12_py310_250213_gbdcc918d_0
  - pynvjitlink=0.7.0=12.9_py310_250625_3693c9cd_hd6618c4
  - pynvml=12.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-lmdb=1.7.2=py310h25320af_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=7_cp310
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-metric-learning=2.8.1=pyh101cb37_1
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py310hf462985_0
  - pyyaml=6.0.2=py310h89163eb_2
  - raft-dask=25.02.00=cuda12_py310_250213_gbdcc918d_0
  - rapids-dask-dependency=25.02.00=py_0
  - rdma-core=58.0=h5888daf_0
  - re2=2025.06.26=h9925aae_1
  - readline=8.2=h8c095d6_2
  - requests=2.32.4=pyhd8ed1ab_0
  - rich=14.0.0=pyh29332c3_0
  - rmm=25.02.00=cuda12_py310_250213_g39b4ccdb_0
  - s2n=1.5.22=h96f233e_0
  - scikit-image=0.20.0=py310h9b08913_1
  - scikit-learn=1.7.0=py310h27f47ee_1
  - scipy=1.15.2=py310h1d65ade_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - spdlog=1.14.1=hed91bc2_1
  - svt-av1=1.4.1=hcb278e6_0
  - tbb=2021.13.0=hceb3a55_1
  - tblib=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2020.6.3=py_0
  - tk=8.6.13=noxft_hd72426e_102
  - toolz=1.0.0=pyhd8ed1ab_1
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu124
  - tornado=6.5.1=py310ha75aee5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - treelite=4.4.1=py310hebdfe98_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ucx=1.18.1=hb51fc76_0
  - ucx-py=0.42.00=py310_250213_gad9cfc2_0
  - ucxx=0.42.00=cuda12_py3.10_250213_g762a6ed_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - faiss-gpu==1.7.2
      - frozenlist==1.7.0
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - multidict==6.6.3
      - nanopq==0.2.2
      - opencv-python==4.12.0.88
      - propcache==0.3.2
      - pyg-lib==0.4.0+pt25cu124
      - pyparsing==3.2.3
      - sympy==1.13.1
      - torch-cluster==1.6.3+pt25cu124
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu124
      - torch-sparse==0.6.18+pt25cu124
      - torch-spline-conv==1.2.2+pt25cu124
      - yarl==1.20.1
prefix: /mnt/hpccs01/home/n11373598/mambaforge/envs/env4